server:
  port: 31002
spring:
  application:
    name: test-freemarker
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    template-loader-path: "classpath:/templates/"
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: xc_cms
logging.level.org.springframework.boot.autoconfigure: ERROR

